### ISSUE TITLE
Make mlxtend available through conda-forge

### ISSUE THREAD

**Issue by rasbt** [rasbt/mlxtend#218]
Based on the number of requests, I think it's a good idea to setup a conda-forge recipe for this project. If someone has experience with this, I'd really welcome your contribution!

**Comment by jlopezpena** [comment]
Hi Sebastian,

since `mlxtend` is already deployed as a `pypi` package creating the conda recipe and binaries is (almost) trivial.

Make sure you have installed `conda-build` in your path, then you can run

```
conda skeleton pipy mlxtend
```

this will create a folder `mlxtend` with the file `meta.yaml` containing the conda recipe on it.

For some reason I didn't really debug, this seems to miss some of `mlxtend` requirements (namely `scikit-learn`, `pandas` and `matplotlib`), but you can just edit the `meta.yaml` file to include them:

```yaml
requirements:
  build:
    - python
    - setuptools
    - numpy >=1.10.4
    - scipy >=0.17
    - scikit-learn >=0.18
    - pandas >=0.17.1
    - matplotlib >=1.5.1
  run:
    - python
    - numpy >=1.10.4
    - scipy >=0.17
    - scikit-learn >=0.18
    - pandas >=0.17.1
    - matplotlib >=1.5.1
```

After this change, by running `conda build mlxtend` it will create the required binaries for your platform and give you its location (in my case, `/home/javier/anaconda3/conda-bld/linux-64/mlxtend-0.7.0-py36h6146f6b_0.tar.bz2`). Then create the binaries for all the other platforms with:

```
conda convert --platform all PATH/mlxtend-0.7.0-py36h6146f6b_0.tar.bz2 -o OUTPUT_PATH
```

which will create all the binaries and put them in `OUTPUT_PATH`.
